#!/bin/bash
source ./environment
docker pull $sourceimage
docker push $docker_latest || true
echo building $docker_tag
docker build -t $docker_tag -t $docker_latest \
    --build-arg sourceimage=$sourceimage .
