#!/bin/bash
source /opt/ros/melodic/setup.bash
cd /ros_catkin_ws

echo import rosinstalls
for i in *.rosinstall; do echo - $i && vcs import src < `echo $i`; done

# prebuild can be used to apply any patch that may be needed to build the sources just downloaded

if [[ -x ./prebuild ]]; then source ./prebuild; fi
catkin config  -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/aarch64-linux-gnu/libpython3.6m.so
catkin build

# postbuild can be used to perform any activity needed after the workspace compilation
if [[ -x ./postbuild ]]; then source ./postbuild; fi

